SUPABASE_DB_HOST="aws-1-ap-southeast-2.pooler.supabase.com"
SUPABASE_DB_PORT="5432"
SUPABASE_DB_NAME="postgres"
SUPABASE_DB_USER="postgres.rwxlmmykndchfhqmizjk"
SUPABASE_DB_PASSWORD="ShadowSignals2026"
